### ISSUE TITLE
Feature request: Allow multiple declarations of the same class

### ISSUE THREAD

**Issue by jonom** [littlegiant/silverstripe-seeder#11]
Think it would be great if you could define multiple sets of 'create' items of the same class with different settings. This would allow for greater variety of seed content and open the door to generating complex/complete site structures - for instance you could declare several items of class 'Page' with unique titles.

Currently something like this won't work because the second 'NewsHolder' declaration overrides the first.

``` yaml
Seeder\Seeder:
  create:
    NewsHolder:
      count: 1
      fields:
        Title: 'News'
    NewsHolder:
      count: 3
      fields:
        Title: 'News Section {$i}'
        Parent: ByTitle(News)
```

**Comment by chrisahhh** [comment]
This is already possible actually. But it's not in the docs unfortunately

```yaml
Seeder\Seeder:
  create:
    -
      class: NewsHolder
      key: News                            # adding a key differentiates between them when using (un)seed -k 
      count: 1
      fields:
        Title: 'News'
    -
      class: NewsHolder
      key: NewSections               # adding a key differentiates between them when using (un)seed -k
      count: 3
      fields:
        Title: 'News Section {$i}'
        Parent: ByTitle(News)
```

However it is limited as there is no way to declare a provider at the top level with this syntax, which is another feature I've wanted to implement for some time, see example below

```yaml
Seeder\Seeder:
  Member: member(user1@mysite.com, password)
  Member: member(user2@mysite.com, password) # there is no way to express this at the moment
```

I'll have a look into implementing this in the new year. If you have any other feature requests let me know

Cheers
